### ISSUE TITLE
Cloning via git directory name issue

### ISSUE THREAD

**Issue by tjlang** [nguy/PyRadarMet#2]
When I clone with git via the link GitHub provides, it creates a PyRadarMet directory. However, the import calls in the source code expect pyradarmet.

**Comment by nguy** [comment]
@tjlang So you have a PyRadarMet overall directory and is the pyradarmet nested there lowercase or mixed as well?

I just changed my local dist to mixed case and still imported 'pyradarmet'

**Comment by tjlang** [comment]
I think this an obsolete issue as it's an installable package, and this error related to when it was a pseudo-package.

**Comment by tjlang** [comment]
Yeah, I just tried a fresh install and ran into no issues like this.
